name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: Run all tests
        type: choice
        options:
          - check_box_test
          - alerts_page_test
          - practice_form_test
          - text_box_test
          - run_all_tests

  #  push:
  #    branches:
  #      - setup-git-actions

  schedule:
    - cron: 30 3 * * 6   # Runs at 03:30 UTC every Saturday
    - cron: 00 10 * * *   # Runs at 10:00 UTC everyday

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        include:
          - BROWSER: "chrome"
          - BROWSER: "edge"
          - BROWSER: "firefox"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install browser
        run: |
          if [[ ${{ matrix.BROWSER }} == "chrome" ]]; then 
            sudo apt-get install -y google-chrome-stable
          elif [[ ${{ matrix.BROWSER }} == "edge" ]]; then 
            sudo apt update && sudo apt install -y microsoft-edge-stable
          elif [[ ${{ matrix.BROWSER }} == "firefox" ]]; then 
            sudo apt update 
            sudo apt install firefox
          fi

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: check box test
        if: "github.event.inputs.deployment_target == 'check_box_test'"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage"
          CREATE_ALLURE_REPORT: true
        run: |
          TEST_NAME="check_box_test"
          REPORT="report/${TEST_NAME}/ctrf-report.json"
          pytest -m "check_box_test" --ctrf $REPORT
          npx github-actions-ctrf $REPORT
        continue-on-error: true

      - name: alerts page test
        if: "github.event.inputs.deployment_target == 'alerts_page_test'"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage"
          CREATE_ALLURE_REPORT: true
        run: |
          TEST_NAME="alerts_page_test"
          REPORT="report/${TEST_NAME}/ctrf-report.json"
          pytest -m "alerts_page_test" --ctrf $REPORT
          npx github-actions-ctrf $REPORT
      - name: Store allure results
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path:
            allure-results/chrome
          retention-days: 1
        continue-on-error: true

      - name: practice form test
        if: "github.event.inputs.deployment_target == 'practice_form_test'"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage"
          CREATE_ALLURE_REPORT: true
        run: |
          TEST_NAME="practice_form_test"
          REPORT="report/${TEST_NAME}/ctrf-report.json"
          pytest -m "practice_form_test" --ctrf $REPORT || true
          npx github-actions-ctrf $REPORT || true
        continue-on-error: true

      - name: text box test
        if: "github.event.inputs.deployment_target == 'text_box_test'"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage"
          CREATE_ALLURE_REPORT: true
        run: |
          TEST_NAME="text_box_test"
          REPORT="report/${TEST_NAME}/ctrf-report.json"
          pytest -m "text_box_test" --ctrf $REPORT
          npx github-actions-ctrf $REPORT
        continue-on-error: true


      - name: run all tests
        if: "github.event.inputs.deployment_target == 'run_all_tests' || github.event.inputs.deployment_target ==
        ''"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage"
          CREATE_ALLURE_REPORT: true
        run: |
          TEST_NAME="run_all_tests"
          REPORT="report/${TEST_NAME}/ctrf-report.json"
          pytest --ctrf $REPORT || true 
          npx github-actions-ctrf $REPORT
        continue-on-error: true

  generate-report:
    runs-on: ubuntu-latest
    needs: test
    name: Generate report
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft' # See 'Supported distributions' for available options
          java-version: '17'
      - run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.23.1/allure-2.23.1.tgz && sudo tar -zxvf allure-2.23.1.tgz -C /opt/ && sudo ln -s /opt/allure-2.23.1/bin/allure /usr/bin/allure
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - run: allure generate -c allure-results -o _site
      - name: Store generated report
        uses: actions/upload-artifact@v3
        with:
          name: _site
          path:
            _site
          retention-days: 1

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Report publication
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.9