name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: Run all tests
        type: choice
        options:
          - check_box_test
          - alerts_page_test
          - practice_form_test
          - text_box_test
          - run_all_tests

  push:
    branches:
      - setup-git-actions

  schedule:
    - cron: 30 3 * * 6   # Runs at 03:30 UTC every Saturday
    - cron: 10 23 * * *   # Runs at 23:00 UTC every Saturday


jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        include:
          - BROWSER: "chrome"
          - BROWSER: "edge"
          - BROWSER: "firefox"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install browser
        run: |
          if [[ ${{ matrix.BROWSER }} == "chrome" ]]; then 
            sudo apt-get install -y google-chrome-stable
          elif [[ ${{ matrix.BROWSER }} == "edge" ]]; then 
            sudo apt update && sudo apt install -y microsoft-edge-stable
          elif [[ ${{ matrix.BROWSER }} == "firefox" ]]; then 
            sudo apt update 
            sudo apt install firefox
          fi

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      #      - name: Create report directory
      #        run: |
      #          REPORT_DIR="report/${{ github.event.inputs.deployment_target }}"
      #          mkdir -p "$REPORT_DIR"
      #          echo "Created report directory: $REPORT_DIR"

      - name: check box test
        if: "github.event.inputs.deployment_target == 'check_box_test' || github.event.inputs.deployment_target ==
        ''"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage"
          REPORT: "report/check_box_test/ctrf-report.json"
        run: |
          pytest -m "check_box_test" --ctrf $REPORT
          npx github-actions-ctrf $REPORT
        continue-on-error: true

      - name: alerts page test
        if: "github.event.inputs.deployment_target == 'alerts_page_test' || github.event.inputs.deployment_target ==
        ''"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage"
          REPORT: "report/alerts_page_test/ctrf-report.json"
        run: |
          pytest -m "alerts_page_test" --ctrf $REPORT
          npx github-actions-ctrf $REPORT
        continue-on-error: true

      - name: practice form test
        if: "github.event.inputs.deployment_target == 'practice_form_test' || github.event.inputs.deployment_target ==
        ''"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage"
          REPORT: "report/practice_form_test/ctrf-report.json"
        run: |
          pytest -m "practice_form_test" --ctrf $REPORT
          npx github-actions-ctrf $REPORT
        continue-on-error: true

      - name: text box test
        if: "github.event.inputs.deployment_target == 'text_box_test' || github.event.inputs.deployment_target ==
        ''"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage"
          REPORT: "report/text_box_test/ctrf-report.json"
        run: |
          pytest -m "text_box_test" --ctrf $REPORT
          npx github-actions-ctrf $REPORT
        continue-on-error: true

      - name: run all tests
        if: "github.event.inputs.deployment_target == 'run_all_tests'"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage"
          REPORT: "report/run_all_tests/ctrf-report.json"
        run: |
          pytest --ctrf $REPORT
          npx github-actions-ctrf $REPORT
#        continue-on-error: true

#      - name: Run CTRF annotations
#        run: npx github-actions-ctrf REPORT_DIR/ctrf-report.json
#        continue-on-error: true
#        if: always()
