name: Automated tests

on:
  #  push
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: practice_form_test
        type: choice
        options:
          - check_box_test
          - alerts_page_test
          - practice_form_test
          - text_box_test
          - Run all tests

  push:
    branches:
    - setup-git-actions

#  schedule:
#    - cron: 30 3 * * 6   # Runs at 03:30 UTC every Saturday


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: check_box_test
        if: "github.event.inputs.deployment_target == 'check_box_test' || github.event.inputs.deployment_target ==
        ''"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage --ctrf $REPORT"
          REPORT: "report/ctrf-report.json"
        run: pytest -m "check_box_test"
      - name: alerts_page_test
        if: "github.event.inputs.deployment_target == 'alerts_page_test'"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage"
        run: pytest -m "alerts_page_test"
      - name: practice_form_test
        if: "github.event.inputs.deployment_target == 'practice_form_test'"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage"
        run: pytest -m "practice_form_test"
      - name: text_box_test
        if: "github.event.inputs.deployment_target == 'text_box_test'"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage"
        run: pytest -m "text_box_test"
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'Run all tests'"
        env:
          REMOTE_OPTIONS: "--headless --no-sandbox --disable-dev-shm-usage"
        run: pytest
      - name: Run CTRF annotations
        run: npx github-actions-ctrf report/ctrf-report.json
        if: always()